### ISSUE TITLE
Criar botão “Ver Todos” em Destaques

### ISSUE THREAD

**Issue by moacirmoda** [lenilsonjr/BVS-WP#2]
- Listar todos os posts;
- Manter índice alfabético e busca;
- Indicar caso o post tenha sido destaque;
- Adicionar excerpt do post;
- Linkar título para página do post;

**Comment by lenilsonjr** [comment]
Implementado no fa4f2b8 e cbee076. Lembrando que para que a listagem de posts funcionar é necessário criar uma página e setar ela como blog nas configurações do WordPress.
